-- =========================================================================
-- Gateway API keys: per-organization scoping
-- =========================================================================
-- Adds `organization_id` to gateway.api_keys so each org owns a single active
-- key used to call api.saoma.io/v1/*. Keys are auto-generated when an org is
-- created and can be regenerated by an org-admin (regenerate = revoke active +
-- issue new, immediately).
--
-- Three org-scoped SECURITY DEFINER functions wrap the existing Vault logic
-- (mirrors the pattern in 20260529120000_gateway_api_keys.sql), and the
-- shared `gateway_verify_api_key` is patched to expose `organization_id` so
-- /v1/* routes can filter Supabase reads by tenant.
-- =========================================================================

-- 1. Tenant column.
ALTER TABLE gateway.api_keys
  ADD COLUMN IF NOT EXISTS organization_id UUID REFERENCES public.organizations(id) ON DELETE CASCADE;

-- 2. One active key per organization (partial unique index).
CREATE UNIQUE INDEX IF NOT EXISTS api_keys_one_active_per_org
  ON gateway.api_keys (organization_id)
  WHERE revoked_at IS NULL AND organization_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_api_keys_organization_id
  ON gateway.api_keys (organization_id);

-- 3. Patch the verify function to surface organization_id in the JSONB
--    so /v1/* routes can scope reads by tenant.
CREATE OR REPLACE FUNCTION public.gateway_verify_api_key(_key TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, vault, extensions
AS $$
DECLARE
  v_prefix    TEXT;
  v_row       gateway.api_keys%ROWTYPE;
  v_decrypted TEXT;
BEGIN
  IF _key IS NULL THEN
    RETURN NULL;
  END IF;

  v_prefix := substring(_key FROM '^(sk_live_[0-9a-f]+)_');
  IF v_prefix IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT * INTO v_row
  FROM gateway.api_keys
  WHERE key_prefix = v_prefix;

  IF NOT FOUND OR v_row.revoked_at IS NOT NULL OR v_row.vault_secret_id IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT decrypted_secret INTO v_decrypted
  FROM vault.decrypted_secrets
  WHERE id = v_row.vault_secret_id;

  IF v_decrypted IS NULL OR v_decrypted <> _key THEN
    RETURN NULL;
  END IF;

  UPDATE gateway.api_keys SET last_used_at = now() WHERE id = v_row.id;

  RETURN jsonb_build_object(
    'id',              v_row.id,
    'name',            v_row.name,
    'hotel_id',        v_row.hotel_id,
    'organization_id', v_row.organization_id,
    'scopes',          to_jsonb(v_row.scopes)
  );
END;
$$;

-- 4. Get the org's active key metadata (NULL if none).
CREATE OR REPLACE FUNCTION public.gateway_get_org_api_key(_org_id UUID)
RETURNS TABLE(
  id                 UUID,
  key_prefix         TEXT,
  scopes             TEXT[],
  rate_limit_per_min INTEGER,
  last_used_at       TIMESTAMPTZ,
  created_at         TIMESTAMPTZ
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT id, key_prefix, scopes, rate_limit_per_min, last_used_at, created_at
  FROM gateway.api_keys
  WHERE organization_id = _org_id
    AND revoked_at IS NULL
  ORDER BY created_at DESC
  LIMIT 1;
$$;

-- 5. Create a key for an org. If an active key already exists, revoke it first
--    (Regenerate semantics — immediate revocation, no grace period).
--    Returns the FULL key in cleartext (shown to the admin once).
CREATE OR REPLACE FUNCTION public.gateway_create_org_api_key(_org_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, vault, extensions
AS $$
DECLARE
  v_prefix    TEXT;
  v_full      TEXT;
  v_secret_id UUID;
  v_id        UUID;
  v_org_name  TEXT;
BEGIN
  IF _org_id IS NULL THEN
    RAISE EXCEPTION 'organization_id is required';
  END IF;

  SELECT name INTO v_org_name FROM public.organizations WHERE id = _org_id;
  IF v_org_name IS NULL THEN
    RAISE EXCEPTION 'organization % not found', _org_id;
  END IF;

  -- Revoke any active key for this org so the partial unique index is satisfied.
  UPDATE gateway.api_keys
    SET revoked_at = now()
    WHERE organization_id = _org_id AND revoked_at IS NULL;

  v_prefix := 'sk_live_' || encode(gen_random_bytes(4), 'hex');
  v_full   := v_prefix || '_' || encode(gen_random_bytes(24), 'hex');

  v_secret_id := vault.create_secret(
    v_full,
    'gateway_apikey_' || v_prefix,
    'API key (org "' || v_org_name || '")'
  );

  INSERT INTO gateway.api_keys (
    name, hotel_id, organization_id, key_prefix, vault_secret_id, scopes, rate_limit_per_min
  )
  VALUES (
    v_org_name,
    NULL,
    _org_id,
    v_prefix,
    v_secret_id,
    ARRAY['venues:read', 'treatments:read', 'bookings:read', 'therapists:read'],
    NULL
  )
  RETURNING id INTO v_id;

  RETURN jsonb_build_object(
    'id',         v_id,
    'key_prefix', v_prefix,
    'api_key',    v_full
  );
END;
$$;

-- 6. Reveal the active key for an org (decrypts from Vault).
CREATE OR REPLACE FUNCTION public.gateway_reveal_org_api_key(_org_id UUID)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, vault, extensions
AS $$
DECLARE
  v_secret_id UUID;
  v_decrypted TEXT;
BEGIN
  SELECT vault_secret_id INTO v_secret_id
  FROM gateway.api_keys
  WHERE organization_id = _org_id AND revoked_at IS NULL
  ORDER BY created_at DESC
  LIMIT 1;

  IF v_secret_id IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT decrypted_secret INTO v_decrypted
  FROM vault.decrypted_secrets
  WHERE id = v_secret_id;

  RETURN v_decrypted;
END;
$$;

-- 7. Lock down execution: service_role only.
REVOKE ALL ON FUNCTION public.gateway_get_org_api_key(UUID)    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.gateway_create_org_api_key(UUID) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.gateway_reveal_org_api_key(UUID) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.gateway_get_org_api_key(UUID)    TO service_role;
GRANT EXECUTE ON FUNCTION public.gateway_create_org_api_key(UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.gateway_reveal_org_api_key(UUID) TO service_role;
