-- Add a short, opaque, URL-safe token to bookings for use in SMS links.
-- Goal: URLs short enough to fit a single SMS segment (~30 chars total),
-- without exposing the sequential booking_id (which would let an attacker
-- iterate through the whole agenda).
--
-- Token = 8 chars from base62 (a-z, A-Z, 0-9) → 62^8 ≈ 218e12 combinations.
-- Generated by gen_random_bytes (pgcrypto) so it's cryptographically random.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION public.gen_booking_short_token()
RETURNS text
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
  alphabet constant text := 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  result text := '';
  i int;
  bytes bytea;
BEGIN
  -- Retry loop to avoid extremely rare collisions.
  FOR attempt IN 1..5 LOOP
    result := '';
    bytes := gen_random_bytes(8);
    FOR i IN 0..7 LOOP
      result := result || substr(alphabet, (get_byte(bytes, i) % 62) + 1, 1);
    END LOOP;

    -- Ensure uniqueness; if collision, retry.
    IF NOT EXISTS (SELECT 1 FROM public.bookings WHERE short_token = result) THEN
      RETURN result;
    END IF;
  END LOOP;

  -- Extremely unlikely fallback: append a timestamp suffix.
  RETURN result || extract(epoch from clock_timestamp())::bigint::text;
END;
$$;

ALTER TABLE public.bookings
  ADD COLUMN IF NOT EXISTS short_token text UNIQUE;

-- Backfill existing rows so old bookings remain manageable via the short URL.
UPDATE public.bookings
SET short_token = public.gen_booking_short_token()
WHERE short_token IS NULL;

-- Default for future inserts.
ALTER TABLE public.bookings
  ALTER COLUMN short_token SET DEFAULT public.gen_booking_short_token();

-- Make it NOT NULL now that backfill is done.
ALTER TABLE public.bookings
  ALTER COLUMN short_token SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_bookings_short_token ON public.bookings(short_token);

COMMENT ON COLUMN public.bookings.short_token IS
  'Opaque 8-char base62 token used in SMS manage URLs (/m/:token). Random, unguessable.';
